#! /usr/local/bin/python3
# -*- coding: utf-8 -*-

import sys
from subprocess import getoutput

COMMAND_PREFIX = "osascript -e \'tell application \"Rdio\" to "

def play():
	"""
	Resumes playback
	"""
	print("playing...")
	getoutput(COMMAND_PREFIX + "play" + "\'")

def pause():
	"""
	Pauses playback
	"""
	print("pausing...")
	getoutput(COMMAND_PREFIX + "pause" + "\'")

def next():
	"""
	Plays the next track
	"""
	getoutput(COMMAND_PREFIX + "play next track" + "\'")
	print("playing next track... : " + getsongname())
def last():
	"""
	Plays the previous song
	"""
	getoutput(COMMAND_PREFIX + "play previous track" + "\'")
	print("playing previous track... : " + getsongname())

def getartist():
	"""
	Returns current artist name
	"""
	return getoutput(COMMAND_PREFIX + "get the artist of the current track\'")

def getsongname():
	"""
	Returns the string of the current song name
	"""
	return getoutput(COMMAND_PREFIX + "get the name of the current track\'")
	
def mute():
	"""
	Mute the player
	"""
	print("Muting...")
	return getoutput(COMMAND_PREFIX + "set the sound volume to 0" + "\'")

def unmute():
	"""
	Unmute the desktop player
	"""
	print("unmuting...")
	return getoutput(COMMAND_PREFIX + "set the sound volume to 100" + "\'")

def quit():
	"""
	Exit the nice way
	"""
	sys.exit(0)

def repl():
	while(True):
		prompt = "" + getartist() + ":" + getsongname() + ">> "
		cmd = input(prompt)
		if cmd == "play": play()
		elif cmd == "pause": pause()
		elif cmd == "next": next()
		elif cmd == "last": last()
		elif cmd == "artist": print(getartist())
		elif cmd == "song" : print(getsongname())
		elif cmd == "mute" : mute()
		elif cmd == "unmute" : unmute()
		elif cmd == "exit" : quit()


if __name__ == "__main__":
	repl()
